# Generated by Django 5.0 on 2023-12-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_created_at_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
